version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - imonir
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
networks:
  imonir:
    external: true

