version: '3.5'

services:
  imonir_front:
    container_name: imonir_front
    restart: 'unless-stopped'
    build: 
      context: frontend
      dockerfile: Dockerfile
    expose:
      - 4100
    volumes:
     - ./frontend:/home/app
     - imonir_front_node_modules:/home/app/node_modules
    env_file:
      - .env.frontend

volumes:
  imonir_front_node_modules:

networks:
  default:
    external:
      name: fullstack
