version: '3'
services:
  backend:
    build: .
    expose:
      - 8000
    volumes:
     - .:/home/app
     - node_modules:/home/app/node_modules
    environment:
      VIRTUAL_PORT: "8000"

volumes: 
  node_modules:

networks:
  default:
    external:
      name: fullstack

